#should install all possibly needed packages
local({r <- getOption("repos")
r["CRAN"] <- "http://cran.r-project.org" 
options(repos=r)
})
install.packages("RCurl")
install.packages("httr")
install.packages("png")
install.packages("pbapply")
install.packages("gplots")
install.packages("gtools")
install.packages("rJava")
install.packages("xlsx")
source("https://bioconductor.org/biocLite.R")
biocLite("GenomicRanges")